/* WARNING PATH HAS BEEN AUTO-GENERATED BY THE PYTHON PARSER. DO NOT TOUCH OR YOU WILL HAVE BAD LUCK 
    FOR ETERNITY AND WILL BE TARGET NO.1 DURING THE ROBOT REVOLUTION. 
    
    Auto Works!
    */
    
    package frc.robot.routes;
    
    /**
    * Stores the paths for auto path1. 
    * @author THANOS
    */
    public class path1 {
        public double[] frontLeftEncoderPositions = {
            3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3
        };
    /*
    ROBOTS RUN THE WORLD, YOU JUST DON'T KNOW IT YET
    */
        public double[] frontRightEncoderPositions = {
            4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4
        };
    /*
    Don't Use Do While loops 
    */
        public double[] backLeftEncoderPositions = {
            5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5
        };
    /*
    Edd, I Hardly Know Her
    */    
        public double[] backRightEncoderPositions = {
            6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6
        };
    }
    /*
    Copyright THANOS 2247
    */
    