/* WARNING PATH HAS BEEN AUTO-GENERATED BY THE PYTHON PARSER. DO NOT TOUCH OR YOU WILL HAVE BAD LUCK 
    FOR ETERNITY AND WILL BE TARGET NO.1 DURING THE ROBOT REVOLUTION. 
    
    Enter The Matrix
    */
    
    package frc.robot.routes;
    
    /**
    * Stores the paths for auto path1. 
    * @author THE SLACKER MENTOR
    */
    public class path1 {
        public double[] frontLeftEncoderPositions = {
            3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3,
			3
        };
    /*
    ROBOTS RUN THE WORLD, YOU JUST DON'T KNOW IT YET
    */
        public double[] frontRightEncoderPositions = {
            4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4,
			4
        };
    /*
    How many programmers does it take to change a light bulb?
None – It’s a hardware problem 
    */
        public double[] backLeftEncoderPositions = {
            5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5,
			5
        };
    /*
    2 + 3 is 5
    */    
        public double[] backRightEncoderPositions = {
            6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6,
			6
        };
    }
    /*
    Copyright THE SLACKER MENTOR 2456
    */
    